services:
  - type: web
    name: cortex-ai-backend
    env: python
    buildCommand: pip install fastapi uvicorn python-multipart python-jose passlib bcrypt
    startCommand: uvicorn api.index:handler --host 0.0.0.0 --port $PORT
    rootDir: ./
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0